# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d38cf22acf34a960ddf3856999de0daf7eaeb5c5e2816f883986a1ff6d686d13b5837e680308ddd8500764be74547ff8005003aa19044a7faaa44df60715a4a6

test:
  secret_key_base: ded5f5fc770142c17e818dd6a36132f3f8dbe027e0eb8db975d80a64f4a1ea3788da4a7b560dd135a608e1dd56039ff45d828254152bd830295ce5c5bac60512

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
